"""Add hotels

Revision ID: c1dbb95bf9af
Revises: 16a2e42d9814
Create Date: 2025-10-08 10:31:50.704502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1dbb95bf9af'
down_revision: Union[str, Sequence[str], None] = '16a2e42d9814'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hotels',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('hotel_admin_oid', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('oid', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('oid')
    )
    op.create_table('rooms',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('hotel_oid', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('room_type', sa.String(), nullable=False),
    sa.Column('bed_type', sa.String(), nullable=False),
    sa.Column('oid', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('oid')
    )
    op.create_table('room_photos',
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('room_oid', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('caption', sa.String(), nullable=True),
    sa.Column('is_cover', sa.Boolean(), nullable=False),
    sa.Column('oid', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['room_oid'], ['rooms.oid'], ),
    sa.PrimaryKeyConstraint('oid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('room_photos')
    op.drop_table('rooms')
    op.drop_table('hotels')
    # ### end Alembic commands ###
