"""Remove hotel admins, update user

Revision ID: 16a2e42d9814
Revises: 1de12e2d48b3
Create Date: 2025-09-26 14:28:38.765321

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = "16a2e42d9814"
down_revision: Union[str, Sequence[str], None] = "1de12e2d48b3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_hotel_admins_phone"), table_name="hotel_admins")
    op.drop_table("hotel_admins")
    op.add_column("users", sa.Column("is_hotel_admin", sa.Boolean(), nullable=True))
    op.execute("UPDATE users SET is_hotel_admin = False WHERE is_hotel_admin IS NULL;")
    op.alter_column("users", "is_hotel_admin", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "is_hotel_admin")
    op.create_table(
        "hotel_admins",
        sa.Column("first_name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("last_name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("middle_name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("phone", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("email", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("password_hash", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("is_banned", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column("oid", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("oid", name=op.f("hotel_admins_pkey")),
    )
    op.create_index(op.f("ix_hotel_admins_phone"), "hotel_admins", ["phone"], unique=False)
    # ### end Alembic commands ###
