"""User add is_superuser

Revision ID: d630f4b82418
Revises: 2a1c9a0ce014
Create Date: 2025-09-24 19:18:27.066088

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d630f4b82418"
down_revision: Union[str, Sequence[str], None] = "2a1c9a0ce014"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("is_superuser", sa.Boolean(), nullable=True))
    op.execute("UPDATE users SET is_superuser = False WHERE is_superuser IS NULL;")
    op.alter_column("users", "is_superuser", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "is_superuser")
    # ### end Alembic commands ###
